DEVICE: 'cpu'
DATASET:
    TRAIN: 'AmzSoftwares'
    TEST: 'AmzSoftwares'
    RATIO: 0.6
DATALOADER:
    NUM_BATCH: 1000  # default 1000
MODEL:
    INPUT_DIM: 768
    DOWNSAMPLE_DIM: (512, )
    SETCONV_DIM: 128
    EMBEDDING_DIM: 128
    MINORITY_CLASSES: (0.0, )
    K: 1
OPTIMIZER:
    MAX_EPOCH: 10  # default 10
